// All mock data and content strings — single source of truth
// Edit here, not in component code

export const CONTENT = {
  listing: {
    overallExperience: 4.8,
    reviewCount: 128,
    likelihoodToRecommend: 4.6,
    valueForMoney: 4.3,
    mostRecentReviewLabel: "2 weeks ago",
    ratingDistribution: [
      { stars: 5, count: 64 },
      { stars: 4, count: 48 },
      { stars: 3, count: 12 },
      { stars: 2, count: 3 },
      { stars: 1, count: 1 },
    ],
    neighbourhoodAverage: 4.5,
    neighbourhoodDistribution: [
      { stars: 5, count: 42 },
      { stars: 4, count: 56 },
      { stars: 3, count: 28 },
      { stars: 2, count: 12 },
      { stars: 1, count: 6 },
    ],
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1450,
    furnished: "Furnished",
    availableFrom: "1 Sept 2026",
    description: "A bright two-bedroom in Marina Gate with full Marina views, a renovated kitchen, and access to the building's pool and gym.",
    houseRules: ["No pets", "No parties", "No subletting"],
    askingPrice: 145000,
    officialImages: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=300&fit=crop",
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=300&fit=crop",
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&h=300&fit=crop",
      "https://images.unsplash.com/photo-1556909122-d5b604d0c90d?w=800&h=300&fit=crop",
      "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800&h=300&fit=crop",
    ],
    communityImages: [
      "https://images.unsplash.com/photo-1600566753086-00e4a9a52033?w=800&h=300&fit=crop",
      "https://images.unsplash.com/photo-1576678927591-c623a629faa0?w=800&h=300&fit=crop",
      "https://images.unsplash.com/photo-1556909739-d6d93c6e992a?w=800&h=300&fit=crop",
    ],
    categoryRatings: {
      building: {
        maintenance: 4.7,
        sharedFacilities: 4.5,
        buildingStaff: 4.8,
        trafficAccess: 4.2,
      },
      apartment: {
        naturalLight: 4.6,
        soundproofing: 3.9,
        storageSpace: 4.1,
      },
    },
    neighbourhoodCategoryRatings: {
      building: {
        maintenance: 4.3,
        sharedFacilities: 4.1,
        buildingStaff: 4.4,
        trafficAccess: 3.8,
      },
      apartment: {
        naturalLight: 4.2,
        soundproofing: 3.5,
        storageSpace: 3.8,
      },
    },
    landlord: {
      memberSince: 2019,
      buildingsListed: 6,
      responsesWithin: "2 hours",
      responseRate: 95,
      bio: "Manages residential properties across Dubai Marina.",
    },
    reviews: [
      {
        alias: "Sarah M.",
        overallExperience: 5.0,
        when: "3 weeks ago",
        headline: "Smooth handover, exactly as listed",
        whatWasGood: "Ahmed was responsive throughout and the unit matched the listing exactly.",
        whatWasBad: "Parking was a little tight for guests.",
        unitTag: "2BR · Apartment",
      },
      {
        alias: "James K.",
        overallExperience: 4.5,
        when: "2 months ago",
        headline: "Great location, well-maintained building",
        whatWasGood: "Building amenities are well maintained and the gym is rarely crowded.",
        whatWasBad: "Minor delay getting the AC serviced, though it was resolved quickly.",
        unitTag: "1BR · Apartment",
      },
      {
        alias: "Fatima A.",
        overallExperience: 5.0,
        when: "2 weeks ago",
        headline: "Best rental experience I've had in Dubai",
        whatWasGood: "Clear communication throughout and a genuinely fair landlord.",
        whatWasBad: "Wifi in the building lobby is patchy, not really Ahmed's fault.",
        unitTag: "3BR · Apartment",
      },
    ],
    similarBuildings: [
      {
        name: "Marina Heights",
        rating: 4.6,
        rentMin: 125000,
        rentMax: 145000,
        image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=300&h=300&fit=crop",
      },
      {
        name: "Emaar Beachfront",
        rating: 4.9,
        rentMin: 160000,
        rentMax: 210000,
        image: "https://images.unsplash.com/photo-1512207736139-e94db471a5d0?w=300&h=300&fit=crop",
      },
      {
        name: "Marina Promenade",
        rating: 4.5,
        rentMin: 115000,
        rentMax: 135000,
        image: "https://images.unsplash.com/photo-1460317442991-0ec209397118?w=300&h=300&fit=crop",
      },
    ],
  },
  landlord: {
    name: "Ahmed Al Farsi",
    initials: "AF",
  },
  property: {
    building: "Marina Gate",
    unit: "Unit 1204",
  },
  negotiation: {
    asking: 145000, // matches listing.askingPrice
    offer: 135000,
    counter: 140000,
    final: 140000,
  },
  appointment: {
    date: "Tue, 19 Aug",
    slots: [
      { time: "10:00 AM", available: true },
      { time: "11:00 AM", available: false },
      { time: "12:00 PM", available: true },
      { time: "1:00 PM", available: true },
      { time: "2:00 PM", available: false },
      { time: "3:00 PM", available: true },
      { time: "4:00 PM", available: true },
      { time: "5:00 PM", available: false },
    ],
    selectedTime: "12:00 PM",
    pendingCopy:
      "We'll notify you as soon as Ahmed Al Farsi responds to your request.",
    confirmedBadge: "Confirmed by Ahmed Al Farsi",
    toast: "Proposed time accepted",
  },
  contract: {
    annualRent: 140000,
    duration: "12 months",
    startDate: "1 Sept 2026",
    moveInDate: "1 Sept 2026",
    paymentSchedule: "Monthly via Keyper",
    securityDeposit: 7000,
    agencyFee: 7000,
    livingFee: 2800,
    dueBefore: 9800,
    clauses: [
      "Security deposit equal to 5% of annual rent",
      "No subletting without written consent",
      "90-day notice period for non-renewal",
    ],
  },
  livingFee: {
    calculation: "140,000 × 0.02",
    total: 2800,
    disclosure: "This fee is non-refundable once paid.",
    supportingLine: "Charged regardless of payment method.",
    paymentMethods: ["Card", "Tabby"],
    tabbyInstallments: {
      count: 4,
      amount: 700,
    },
    confirmationCopy: "Marina Gate, Unit 1204 has been removed from active listings.",
  },
  documents: {
    items: [
      { name: "Emirates ID", verify: true },
      { name: "Passport", verify: true },
      { name: "Visa", verify: true },
    ],
    timings: [1500, 2000, 2500],
  },
  ejari: {
    steps: [
      "Generating",
      "Ready for review",
      "Sent for e-signature",
      "Both parties signed",
      "Filed",
    ],
    midFlowCopy: "Complete your signature in the REST app",
    midFlowDetail:
      "This step happens outside Livingin — the REST app will confirm back to us automatically.",
    midFlowButton: "I've Signed via REST",
    filedBadge: "Ejari filed",
  },
  deposit: {
    accountName: "Ahmed Al Farsi",
    bank: "Emirates NBD",
    iban: "AE07 0331 2345 6789 0123 456",
    amount: 7000,
    confirmationBadge: "Receipt confirmed by landlord",
    confirmationHero: "AED 7,000 received",
  },
  rentSetup: {
    provider: "Keyper",
    handoffCopy:
      "You're leaving Livingin's flow to finish setup with Keyper, our monthly-payment partner.",
    connectingCopy: "Connecting to Keyper…",
    connectedBadge: "Keyper connected",
    firstPaymentAmount: 11667,
    firstPaymentDate: "1 Sept 2026",
  },
  moveIn: {
    confirmedCopy: "You're all set",
    checklist: [
      "Living fee paid",
      "Ejari filed",
      "Deposit confirmed",
      "Keyper connected",
    ],
    marketplaceCategories: [
      {
        name: "Moving",
        icon: "Package",
        image: "https://images.unsplash.com/photo-1552320554-5fefe8c9ef14?w=400&h=400&fit=crop",
      },
      {
        name: "Internet",
        icon: "Wifi",
        image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400&h=400&fit=crop",
      },
      {
        name: "Deep Clean",
        icon: "Sparkles",
        image: "https://images.unsplash.com/photo-1527399216261-38c75010e6c9?w=400&h=400&fit=crop",
      },
      {
        name: "Regular Clean",
        icon: "BarChart3",
        image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=400&fit=crop",
      },
    ],
    marketplaceProviders: [
      {
        category: "Moving",
        name: "ProMove Logistics",
        rate: "Livingin rate",
        price: 850,
      },
      {
        category: "Internet",
        name: "Etisalat Premium",
        rate: "Livingin rate",
        price: 99,
      },
      {
        category: "Deep Clean",
        name: "Fresh Start Cleaning",
        rate: "Livingin rate",
        price: 450,
      },
      {
        category: "Regular Clean",
        name: "Fresh Start Cleaning",
        rate: "Livingin rate",
        price: 150,
      },
    ],
  },
  timings: {
    landlordAccept: 2000,
    landlordCounter: 2000,
    paymentProcess: 1500,
    documentVerify: [1500, 2000, 2500],
    ejariAuto: 1500,
    landlordDepositConfirm: 2000,
    keyperConnect: 1800,
    orderProcess: 1500,
  },
};
